package apolo.vendedores.com.utilidades

class TablasSincronizacion {

//    var tablasReportes : TablasReportes = TablasReportes()
//    var tablasVisitas  : TablasVisitas  = TablasVisitas()
//    var tablasInformes : TablasInformes = TablasInformes()

    fun listaSQLCreateTables(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0 , SentenciasSQL.createTableClienteListPrec())
        lista.add(1 , SentenciasSQL.createTableSvmArticulosPrecios())
        lista.add(2 , SentenciasSQL.createTableSvmClienteVendedor())
        lista.add(3 , SentenciasSQL.createTableSvmCondicionVenta())
        lista.add(4 , SentenciasSQL.createTableSvmStArticulos())
        lista.add(5 ,SentenciasSQL.createTableSvmVendedorPedido())
        lista.add(6 ,SentenciasSQL.createTableSvmDeudaCliente())
        lista.add(7 ,SentenciasSQL.createTableSvmMetasPuntoPorLinea())
        lista.add(8,SentenciasSQL.createTableSvmMetasPuntoPorCliente())
        lista.add(9,SentenciasSQL.createTableSvmPedidosSinStockRep())
        lista.add(10,SentenciasSQL.createTableSvmNegociacionVenta())
        lista.add(11,SentenciasSQL.createTableSvmPedidosEnReparto())
        lista.add(12,SentenciasSQL.createTableSvmRebotesPorCliente())
        lista.add(13,SentenciasSQL.createTableSvmCiudades())
        lista.add(14,SentenciasSQL.createTableSvmTablaVisitas())
        lista.add(15,SentenciasSQL.createTableSvmTipoCliente())
        lista.add(16,SentenciasSQL.createTableSvmCondicionVentaCliente())
        lista.add(17,SentenciasSQL.createTableSvmPreciosFijos())
        lista.add(18,SentenciasSQL.createTableSvmLiqComisionVendedor())
        lista.add(19,SentenciasSQL.createTableSvmModuloComisionVend())
        lista.add(20,SentenciasSQL.createTableSvmCondVentaVendedor())
        lista.add(21,SentenciasSQL.createTableSvmEvolDiariaVenta())
        lista.add(22,SentenciasSQL.createTableVtvPreciosFijos())
        lista.add(23,SentenciasSQL.createTableStvCategoriaPalm())
        lista.add(24,SentenciasSQL.createTableSpmMotivoNoVenta())
        lista.add(25,SentenciasSQL.createTableSvmPromocionesPorPerfiles())
        lista.add(26,SentenciasSQL.createTableSvmListadoPedido())
        lista.add(27,SentenciasSQL.createTableSvmDiasTomaFotoCliente())
        lista.add(28,SentenciasSQL.createTableSvmSegVisitasSemanal())
        lista.add(29,SentenciasSQL.createTableSvmPromocionesArtCab())
        lista.add(30,SentenciasSQL.createTableSvmPromocionesArtDet())
        lista.add(31,SentenciasSQL.createTableSvmMensajeConclusion())
        lista.add(32,SentenciasSQL.createTableSvmSurtidoEficiente())
        lista.add(33,SentenciasSQL.createTableSvmLiqPremiosVend())
        lista.add(34,SentenciasSQL.createTableSvmProduccionSemanalVend())
        lista.add(35,SentenciasSQL.createTableSvmRuteoSemanalClienteVend())
        lista.add(36,SentenciasSQL.createTableSvmCoberturaVisVendedores())
        lista.add(37,SentenciasSQL.createTableRhvLiquidacionFuerzaVenta())
        lista.add(38,SentenciasSQL.createTableSvmVtMotivosSdDev())
        lista.add(39,SentenciasSQL.createTableFvvLiqCuotaXUndNegVend())
        lista.add(40,SentenciasSQL.createTableSvmCoberturaMensualVend())
        lista.add(41,SentenciasSQL.createTableFvvCobSemanalVend())
//        lista.add(47,SentenciasSQL.)
//        lista.add(48,SentenciasSQL.)
//        lista.add(49,SentenciasSQL.)

        return lista
    }

    fun listaSQLCreateIndexes(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0 , SentenciasSQL.createIndexSvmClienteVendedor())
        lista.add(1 , SentenciasSQL.createIndexArticuloPrecioSvmArticulosPrecios())
        lista.add(2 , SentenciasSQL.createIndexCodArticuloSvmArticulosPrecios())
        lista.add(3 , SentenciasSQL.createIndexCodArticuloSvmStArticulos())
        lista.add(4 , SentenciasSQL.createIndexDescArticuloSvmStArticulos())
        lista.add(5 , SentenciasSQL.createIndexCodBarraStArticulos())
        lista.add(6 , SentenciasSQL.createTableSvmDeudaCliente())
//        lista.add(7 , SentenciasSQL.createIndexIndSurtidoEficiente())
//        lista.add(8 , SentenciasSQL.createIndexCodClienteSurtidoEficiente())
//        lista.add(9 , SentenciasSQL.createIndexCodSubclienteSurtidoEficiente())
//        lista.add(10, SentenciasSQL.createIndexTipClienteSurtidoEficiente())

        return lista
    }

    fun listaCamposSincronizacion(): ArrayList<ArrayList<String>> {
        val lista : ArrayList<ArrayList<String>> = ArrayList()
        lista.add(0 ,camposTablaSvmClienteListPrec())
        lista.add(1 ,camposTablaSvmArticulosPrecios())
        lista.add(2 ,camposTablaSvmClienteVendedor())
        lista.add(3 ,camposTablaSvmCondicionVenta())
        lista.add(4 ,camposTablaSvmStArticulos())
//        lista.add(5 ,camposTablaSvmUltimaVentaCliente())
        lista.add(5 ,camposTablaSvmVendedorPedido())
        lista.add(6 ,camposTablaSvmDeudaCliente())
//        lista.add(8 ,camposTablaSvmPromArticulosTarCred())
        lista.add(7 ,camposTablaSvmMetasPuntoPorLinea())
        lista.add(8,camposTablaSvmMetasPuntoPorCliente())
        lista.add(9,camposTablaSvmPedidosSinStockRep())
        lista.add(10,camposTablaSvmNegociacionVenta())
        lista.add(11,camposTablaSvmPedidosEnReparto())
        lista.add(12,camposTablaSvmRebotesPorCliente())
        lista.add(13,camposTablaSvmCiudades())
        lista.add(14,camposTablaSvmTablaVisitas())
        lista.add(15,camposTablaSvmTipoCliente())
        lista.add(16,camposTablaSvmCondicionVentaCliente())
        lista.add(17,camposTablaSvmPreciosFijos())
        lista.add(18,camposTablaSvmLiqComisionVendedor())
        lista.add(19,camposTablaSvmModuloComisionVend())
//        lista.add(22,camposTablaSvmDiasVisitaCliente())
        lista.add(20,camposTablaSvmCondVentaVendedor())
        lista.add(21,camposTablaSvmEvolDiariaVenta())
        lista.add(22,camposTablaSvmVtvPreciosFijosMod())
        lista.add(23,camposTablaStvCategoriaPalm())
//        lista.add(27,camposTablaSvmRetornoComentario())
        lista.add(24,camposTablaSpmMotivoNoVenta())
        lista.add(25,camposTablaSvmPromocionesPorPerfiles())
        lista.add(26,camposTablaSvmListadoPedidos())
        lista.add(27,camposTablaSvmDiasTomaFotoCliente())
        lista.add(28,camposTablaSvmSegVisitasSemanal())
//        lista.add(33,camposTablaCcvMotivoSolTarjCred())
        lista.add(29,camposTablaSvmPromocionesArtCab())
        lista.add(30,camposTablaSvmPromocionesArtDet())
        lista.add(31,camposTablaSvmMensajeConclusion())
        lista.add(32,camposTablaSvmSurtidoEficiente())
        lista.add(33,camposTablaSvmLiqPremiosVend())
        lista.add(34,camposTablaSvmProduccionSemanalVend())
        lista.add(35,camposTablaSvmRuteoSemanalClienteVend())
        lista.add(36,camposTablaSvmCoberturaVisVendedores())
        lista.add(37,camposTablaRhvLiquidacionFuerzaVenta())
        lista.add(38,camposTablaSvmVtMotivosSodDev())
        lista.add(39,camposTablaFvvLiqCuotaXUndNegVend())
        lista.add(40,camposTablaSvmCoberturaMensualVend())
        lista.add(41,camposTablaFvvCobSemanalVend())

        return lista
    }

   /* fun listaVistas(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
//        lista.add(0 ,SentenciasSQL.venRuteoSemanalClienteVendedor())
//        lista.add(1 ,camposTablaSvmArticulosPrecios())
//        lista.add(2 ,camposTablaSvmClienteVendedor())
//        lista.add(3 ,camposTablaSvmCondicionVenta())
//        lista.add(4 ,camposTablaSvmStArticulos())
////        lista.add(5 ,camposTablaSvmUltimaVentaCliente())
//        lista.add(5 ,camposTablaSvmVendedorPedido())
//        lista.add(6 ,camposTablaSvmDeudaCliente())
////        lista.add(8 ,camposTablaSvmPromArticulosTarCred())
//        lista.add(7 ,camposTablaSvmMetasPuntoPorLinea())
//        lista.add(8,camposTablaSvmMetasPuntoPorCliente())
//        lista.add(9,camposTablaSvmPedidosSinStockRep())
//        lista.add(10,camposTablaSvmNegociacionVenta())
//        lista.add(11,camposTablaSvmPedidosEnReparto())
//        lista.add(12,camposTablaSvmRebotesPorCliente())
//        lista.add(13,camposTablaSvmCiudades())
//        lista.add(14,camposTablaSvmTablaVisitas())
//        lista.add(15,camposTablaSvmTipoCliente())
//        lista.add(16,camposTablaSvmCondicionVentaCliente())
//        lista.add(17,camposTablaSvmPreciosFijos())
//        lista.add(18,camposTablaSvmLiqComisionVendedor())
//        lista.add(19,camposTablaSvmModuloComisionVend())
////        lista.add(22,camposTablaSvmDiasVisitaCliente())
//        lista.add(20,camposTablaSvmCondVentaVendedor())
//        lista.add(21,camposTablaSvmEvolDiariaVenta())
//        lista.add(22,camposTablaSvmVtvPreciosFijosMod())
//        lista.add(23,camposTablaStvCategoriaPalm())
////        lista.add(27,camposTablaSvmRetornoComentario())
//        lista.add(24,camposTablaSpmMotivoNoVenta())
//        lista.add(25,camposTablaSvmPromocionesPorPerfiles())
//        lista.add(26,camposTablaSvmListadoPedidos())
//        lista.add(27,camposTablaSvmDiasTomaFotoCliente())
//        lista.add(28,camposTablaSvmSegVisitasSemanal())
////        lista.add(33,camposTablaCcvMotivoSolTarjCred())
//        lista.add(29,camposTablaSvmPromocionesArtCab())
//        lista.add(30,camposTablaSvmPromocionesArtDet())
//        lista.add(31,camposTablaSvmMensajeConclusion())
//        lista.add(32,camposTablaSvmSurtidoEficiente())
//        lista.add(33,camposTablaSvmLiqPremiosVend())
//        lista.add(34,camposTablaSvmProduccionSemanalVend())
//        lista.add(35,camposTablaSvmRuteoSemanalClienteVend())
//        lista.add(36,camposTablaSvmCoberturaVisVendedores())
//        lista.add(37,camposTablaRhvLiquidacionFuerzaVenta())
//        lista.add(38,camposTablaSvmVtMotivosSodDev())
//        lista.add(39,camposTablaFvvLiqCuotaXUndNegVend())
//        lista.add(40,camposTablaSvmCoberturaMensualVend())
//        lista.add(41,camposTablaFvvCobSemanalVend())

        return lista
    }
*/
    private fun camposTablaSvmArticulosPrecios(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"MODULO")
        lista.add(3,"COD_LISTA_PRECIO")
        lista.add(4,"COD_ARTICULO")
        lista.add(5,"DESC_ARTICULO")
        lista.add(6,"PREC_CAJA")
        lista.add(7,"PREC_UNID")
        lista.add(8,"COD_UNIDAD_MEDIDA")
        lista.add(9,"PORC_IVA")
        lista.add(10,"REFERENCIA")
        lista.add(11,"MULT")
        lista.add(12,"DIV")
        lista.add(13,"IND_LIM_VENTA")
        lista.add(14,"COD_LINEA")
        lista.add(15,"COD_FAMILIA")
        lista.add(16,"COD_BARRA")
        lista.add(17,"CANT_MINIMA")
        lista.add(18,"PORC_DESCUENTO")
        return lista
    }
    private fun camposTablaSvmClienteListPrec(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_CLIENTE")
        lista.add(2,"COD_SUBCLIENTE")
        lista.add(3,"COD_VENDEDOR")
        lista.add(4,"COD_LISTA_PRECIO")
        lista.add(5,"DESC_LISTA")
        lista.add(6,"IND_DEFECTO")
        lista.add(7,"COD_MONEDA")
        lista.add(8,"DECIMALES")
        return lista
    }
    private fun camposTablaSvmClienteVendedor(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_CLIENTE")
        lista.add(2,"COD_SUBCLIENTE")
        lista.add(3,"DESC_SUBCLIENTE")
        lista.add(4,"DESC_CLIENTE")
        lista.add(5,"COD_VENDEDOR")
        lista.add(6,"TELEFONO")
        lista.add(7,"RUC")
        lista.add(8,"TIP_CAUSAL")
        lista.add(9,"DESC_CIUDAD")
        lista.add(10,"DESC_ZONA")
        lista.add(11,"DESC_REGION")
        lista.add(12,"DIRECCION")
        lista.add(13,"TELEFONO")
        lista.add(14,"COD_SUCURSAL")
        lista.add(15,"DESC_TIPO")
        lista.add(16,"COD_CONDICION")
        lista.add(17,"DESC_CONDICION")
        lista.add(18,"LIMITE_CREDITO")
        lista.add(19,"TOT_DEUDA")
        lista.add(20,"SALDO")
        lista.add(21,"FEC_VISITA")
        lista.add(22,"IND_VISITA")
        lista.add(23,"COD_ZONA")
        lista.add(24,"TIPO_CONDICION")
        lista.add(25,"IND_DIRECTA")
        lista.add(26,"IND_ATRAZO")
        lista.add(27,"FRECUENCIA")
        lista.add(28,"COMENTARIO")
        lista.add(29,"IND_ESP")
        lista.add(30,"CATEGORIA")
        lista.add(31,"TELEFONO2")
        lista.add(32,"LATITUD")
        lista.add(33,"LONGITUD")
        lista.add(34,"CERCA_DE")
        lista.add(35,"IND_CADUCADO")
        lista.add(36,"TIP_CLIENTE")
        lista.add(37,"IND_VITRINA")
        lista.add(38,"FOTO_FACHADA")
        lista.add(39,"TIEMPO_MIN")
        lista.add(40,"TIEMPO_MAX")
        lista.add(41,"SOL_TARG")
        lista.add(42,"DIAS_INICIAL")
        return lista
    }
    private fun camposTablaSvmCondicionVenta(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_CONDICION_VENTA")
        lista.add(2,"DESCRIPCION")
        lista.add(3,"TIPO_CONDICION")
        lista.add(4,"ABREVIATURA")
        lista.add(5,"DIAS_INICIAL")
        lista.add(6,"MONTO_MIN_DESC")
        lista.add(7,"PORC_DESC")
        return lista
    }
    private fun camposTablaSvmStArticulos(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_ARTICULO")
        lista.add(2,"DESC_ARTICULO")
        lista.add(3,"COD_UNIDAD_REL")
        lista.add(4,"REFERENCIA")
        lista.add(5,"MULT")
        lista.add(6,"DIV")
        lista.add(7,"COD_IVA")
        lista.add(8,"PORC_IVA")
        lista.add(9,"COD_LINEA")
        lista.add(10,"COD_FAMILIA")
        lista.add(11,"CANT_MINIMA")
        lista.add(12,"CANT_EXIST")
        lista.add(13,"COD_BARRA")
        lista.add(14,"IND_BASICO")
        return lista
    }
    /*private fun camposTablaSvmUltimaVentaCliente(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_CLIENTE")
        lista.add(2,"COD_VENDEDOR")
        lista.add(3,"COD_SUBCLIENTE")
        lista.add(4,"FEC_COMPROBANTE")
        lista.add(5,"COD_ARTICULO")
        lista.add(6,"PRECIO_UNITARIO")
        lista.add(7,"CANTIDAD")
        lista.add(8,"DESC_UNIDAD")
        lista.add(9,"SIGLAS")
        lista.add(10,"DESC_ARTICULO")
        lista.add(11,"DECIMALES")
        return lista
    }*/
    private fun camposTablaSvmVendedorPedido(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"DESC_VENDEDOR")
        lista.add(3,"IND_PALM")
        lista.add(4,"TIPO")
        lista.add(5,"SERIE")
        lista.add(6,"NUMERO")
        lista.add(7,"FECHA")
        lista.add(8,"COD_CLI_VEND")
        lista.add(9,"COD_PERSONA")
        lista.add(10,"RANGO")
        lista.add(11,"MIN_FOTOS")
        lista.add(12,"MAX_FOTOS")
        lista.add(13,"PER_VENDER")
        lista.add(14,"PER_PRESENCIAL")
        lista.add(15,"HORA")
        lista.add(16,"VERSION_SISTEMA")
        lista.add(17,"PER_ASISTENCIA")
        lista.add(18,"FRECUENCIA_RASTREO")
        lista.add(19,"HORA_INICIO")
        lista.add(20,"HORA_FIN")
        lista.add(21,"TIEMPO_ASISTENCIA")
        lista.add(22,"IND_FOTO")
        lista.add(23,"MIN_VENTA")
        lista.add(24,"PER_MARC_ASIS")
        lista.add(25,"VENT_CON_MARC")
        lista.add(26,"VERSION")


//        lista.add(28,"ULTIMA_VEZ")
//        lista.add(29,"ultima_sincro")
        return lista
    }
    private fun camposTablaSvmDeudaCliente(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_CLIENTE")
        lista.add(2,"COD_SUBCLIENTE")
        lista.add(3,"COD_VENDEDOR")
        lista.add(4,"FEC_EMISION")
        lista.add(5,"FEC_VENCIMIENTO")
        lista.add(6,"TIP_DOCUMENTO")
        lista.add(7,"NRO_DOCUMENTO")
        lista.add(8,"DIA_ATRAZO")
        lista.add(9,"ABREVIATURA")
        lista.add(10,"SALDO_CUOTA")
        return lista
    }
    /*private fun camposTablaSvmPromArticulosTarCred(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"NRO_PROMOCION")
        lista.add(2,"COD_CONDICION_VENTA")
        lista.add(3,"COD_ARTICULO")
        lista.add(4,"DESC_ARTICULO")
        lista.add(5,"PORC_DESCUENTO")
        lista.add(6,"DESCRIPCION")
        lista.add(7,"COMENTARIO")
        return lista
    }*/
    private fun camposTablaSvmMetasPuntoPorLinea(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"DESC_VENDEDOR")
        lista.add(3,"COD_CATEGORIA")
        lista.add(4,"DESC_CATEGORIA")
        lista.add(5,"DESC_GTE_MARKETIN")
        lista.add(6,"DESC_MODULO")
        lista.add(7,"COD_SUPERVISOR")
        lista.add(8,"DESC_SUPERVISOR")
        lista.add(9,"MAYOR_VENTA")
        lista.add(10,"VENTA_MES1")
        lista.add(11,"VENTA_MES2")
        lista.add(12,"META")
        lista.add(13,"MES_1")
        lista.add(14,"MES_2")
        lista.add(15,"NRO_ORD_MAG")
        lista.add(16,"ORD_GTE_MARK")
        lista.add(17,"ORD_CATEGORIA")
        return lista
    }
    private fun camposTablaSvmMetasPuntoPorCliente(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"DESC_VENDEDOR")
        lista.add(3,"CODIGO")
        lista.add(4,"NOM_SUBCLIENTE")
        lista.add(5,"CIUDAD")
        lista.add(6,"COD_SUPERVISOR")
        lista.add(7,"DESC_SUPERVISOR")
        lista.add(8,"LISTA_PRECIO")
        lista.add(9,"MAYOR_VENTA")
        lista.add(10,"VENTA_3")
        lista.add(11,"MIX_3")
        lista.add(12,"VENTA_4")
        lista.add(13,"MIX_4")
        lista.add(14,"METAS")
        lista.add(15,"TOT_SURTIDO")
        lista.add(16,"MES_1")
        lista.add(17,"MES_2")
        return lista
    }
    private fun camposTablaSvmPedidosSinStockRep(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"ORIGEN")
        lista.add(2,"DESC_DEPOSITO")
        lista.add(3,"FEC_COMPROBANTE")
        lista.add(4,"COD_CLIENTE")
        lista.add(5,"CLIENTE")
        lista.add(6,"COD_VENDEDOR")
        lista.add(7,"VENDEDOR")
        lista.add(8,"SUPERVISOR")
        lista.add(9,"COD_ARTICULO")
        lista.add(10,"ARTICULO")
        lista.add(11,"CANTIDAD")
        lista.add(12,"PRECIO_UNITARIO")
        lista.add(13,"MONTO_TOTAL")
        lista.add(14,"PEDIDO")
        lista.add(15,"DECIMALES")
        lista.add(16,"DESC_MOTIVO")
        return lista
    }
    private fun camposTablaSvmNegociacionVenta(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"FEC_COMPROBANTE")
        lista.add(2,"COD_CLIENTE")
        lista.add(3,"DESC_SUBCLIENTE")
        lista.add(4,"COD_VENDEDOR")
        lista.add(5,"COD_LISTA_PRECIO")
        lista.add(6,"COD_SUPERVISOR")
        lista.add(7,"NOM_SUPERVISOR")
        lista.add(8,"COD_ARTICULO")
        lista.add(9,"DESC_ARTICULO")
        lista.add(10,"REFERENCIA")
        lista.add(11,"CANTIDAD")
        lista.add(12,"PRECIO_LISTA")
        lista.add(13,"PRECIO_SOLIC")
        lista.add(14,"PORC_DESCUENTO")
        lista.add(15,"TOTAL_DESC_OTORG")
        lista.add(16,"DECIMALES")
        lista.add(17,"IND_AUT")
        lista.add(18,"OBSERVACION")
        return lista
    }
    private fun camposTablaSvmPedidosEnReparto(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"NRO_PLANILLA")
        lista.add(3,"DESC_REPARTIDOR")
        lista.add(4,"TEL_REPARTIDOR")
        lista.add(5,"FEC_PLANILLA")
        lista.add(6,"FEC_COMPROBANTE")
        lista.add(7,"TIP_COMPROBANTE")
        lista.add(8,"NRO_COMPROBANTE")
        lista.add(9,"COD_CLIENTE")
        lista.add(10,"COD_SUBCLIENTE")
        lista.add(11,"NOM_SUBCLIENTE")
        lista.add(12,"SIGLAS")
        lista.add(13,"DECIMALES")
        lista.add(14,"ESTADO")
        lista.add(15,"TOT_COMPROBANTE")
        return lista
    }
    private fun camposTablaSvmRebotesPorCliente(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"CODIGO")
        lista.add(3,"DESC_PENALIDAD")
        lista.add(4,"MONTO_TOTAL")
        lista.add(5,"FECHA")
        return lista
    }
    private fun camposTablaSvmCiudades(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"COD_PAIS")
        lista.add(3,"DESC_PAIS")
        lista.add(4,"COD_DEPARTAMENTO")
        lista.add(5,"DESC_DEPARTAMENTO")
        lista.add(6,"COD_CIUDAD")
        lista.add(7,"DESC_CIUDAD")
        lista.add(8,"FRECUENCIA")
        return lista
    }
    private fun camposTablaSvmTablaVisitas(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"CODIGO")
        lista.add(2,"DESCRIPCION")
        lista.add(3,"FRECUENCIA")
        return lista
    }
    private fun camposTablaSvmTipoCliente(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"CODIGO")
        lista.add(1,"COD_SUBTIPO")
        lista.add(2,"DESC_CANAL_VENTA")
        lista.add(3,"DESCRIPCION")
        return lista
    }
    private fun camposTablaSvmCondicionVentaCliente(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_CONDICION_VENTA")
        lista.add(2,"DESCRIPCION")
        lista.add(3,"TIPO_CONDICION")
        lista.add(4,"ABREVIATURA")
        lista.add(5,"DIAS_INICIAL")
        return lista
    }
    private fun camposTablaSvmPreciosFijos(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"COD_LISTA_PRECIO")
        lista.add(3,"DESC_LISTA_PRECIO")
        return lista
    }
    /*falto agregar*/private fun camposTablaSvmLiqComisionVendedor(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_CONCEPTO")
        lista.add(1,"DESC_CONCEPTO")
        lista.add(2,"MONTO")
        lista.add(3,"TIPO")
        lista.add(4,"NRO_ORDEN")
        lista.add(5,"NRO_CUOTA")
        lista.add(6,"FEC_HASTA")
        lista.add(7,"COD_MONEDA")
        lista.add(8,"DECIMALES")
        lista.add(9,"SIGLAS")
        lista.add(10,"COMENT")
        return lista
    }
    /*falto agregar*/private fun camposTablaSvmModuloComisionVend(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_CONCEPTO")
        lista.add(1,"DESC_CONCEPTO")
        lista.add(2,"DESC_MODULO")
        lista.add(3,"MONTO_VENTA")
        lista.add(4,"MONTO_COMISION")
        lista.add(5,"FEC_FINAL")
        lista.add(6,"TOT_VENTAS")
        lista.add(7,"TOT_COMISION")
        return lista
    }
    /*private fun camposTablaSvmDiasVisitaCliente(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_CLIENTE")
        lista.add(1,"DESC_CLIENTE")
        lista.add(2,"COD_SUBCLIENTE")
        lista.add(3,"DESC_SUBCLIENTE")
        lista.add(4,"COD_VISITA_ACTUAL")
        lista.add(5,"DESC_VISITA_ACTUAL")
        return lista
    }*/
    private fun camposTablaSvmCondVentaVendedor(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"COD_LISTA_PRECIO")
        lista.add(3,"COD_CLIENTE")
        lista.add(4,"COD_SUBCLIENTE")
        lista.add(5,"COD_CONDICION_VENTA")
        return lista
    }
    private fun camposTablaSvmEvolDiariaVenta(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"DESC_VENDEDOR")
        lista.add(3,"PEDIDO_2_ATRAS")
        lista.add(4,"PEDIDO_1_ATRAS")
        lista.add(5,"TOTAL_PEDIDOS")
        lista.add(6,"TOTAL_FACT")
        lista.add(7,"META_VENTA")
        lista.add(8,"META_LOGRADA")
        lista.add(9,"PROY_VENTA")
        lista.add(10,"TOTAL_REBOTE")
        lista.add(11,"TOTAL_DEVOLUCION")
        lista.add(12,"CANT_CLIENTES")
        lista.add(13,"CANT_POSIT")
        lista.add(14,"EF_VISITA")
        lista.add(15,"DIA_TRAB")
        lista.add(16,"PUNTAJE")
        lista.add(17,"SURTIDO_EF")
        return lista
    }
    private fun camposTablaSvmVtvPreciosFijosMod(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"COD_ARTICULO")
        lista.add(3,"DESC_ARTICULO")
        lista.add(4,"COD_LISTA_PRECIO")
        lista.add(5,"COD_UNIDAD_MEDIDA")
        lista.add(6,"REFERENCIA")
        lista.add(7,"FEC_VIGENCIA")
        lista.add(8,"PRECIO_ANT")
        lista.add(9,"PRECIO_ACT")
        lista.add(10,"DECIMALES")
        lista.add(11,"TIPO")
        return lista
    }
    private fun camposTablaStvCategoriaPalm(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"COD_CATEGORIA")
        lista.add(3,"DESC_CATEGORIA")
        lista.add(4,"COD_SEGMENTO")
        lista.add(5,"DESC_SEGMENTO")
        lista.add(6,"ORDEN")
        lista.add(7,"TIPO")
        lista.add(8,"COD_TIP_CLIENTE")
        return lista
    }
    /*private fun camposTablaSvmRetornoComentario(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"FEC_ENTRADA")
        lista.add(2,"FEC_SALIDA")
        lista.add(3,"COD_PROMOTOR")
        lista.add(4,"COD_CLIENTE")
        lista.add(5,"COD_SUBCLIENTE")
        lista.add(6,"COD_CATEGORIA")
        lista.add(7,"COD_SEGMENTO")
        lista.add(8,"TIPO")
        lista.add(9,"PUNTUACION")
        lista.add(10,"COMENTARIO_SUPERVISOR")
        return lista
    }*/
    private fun camposTablaSpmMotivoNoVenta(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_MOTIVO")
        lista.add(2,"CIERRA")
        lista.add(3,"DESC_MOTIVO")
        return lista
    }
    private fun camposTablaSvmPromocionesPorPerfiles(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"TIP_CLIENTE")
        lista.add(2,"NRO_PROMOCION")
        lista.add(3,"DESCRIPCION")
        lista.add(4,"COMENTARIO")
        lista.add(5,"FEC_INI_PROMO")
        lista.add(6,"FEC_FIN_PROMO")
        lista.add(7,"COD_ARTICULO")
        return lista
    }
    private fun camposTablaSvmListadoPedidos(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"NRO_PEDIDO")
        lista.add(3,"FEC_COMPROBANTE")
        lista.add(4,"COD_CLIENTE")
        lista.add(5,"COD_SUBCLIENTE")
        lista.add(6,"NOM_SUBCLIENTE")
        lista.add(7,"SIGLAS")
        lista.add(8,"DECIMALES")
        lista.add(9,"TOT_COMPROBANTE")
        lista.add(10,"OBSERVACIONES")
        return lista
    }
    private fun camposTablaSvmDiasTomaFotoCliente(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_TIP_CLIENTE")
        lista.add(2,"FEC_INICIO")
        lista.add(3,"FEC_FIN")
        return lista
    }
    private fun camposTablaSvmSegVisitasSemanal(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"FEC_MOVIMIENTO")
        lista.add(3,"FEC_INICIO")
        lista.add(4,"FEC_FIN")
        lista.add(5,"CANTIDAD")
        lista.add(6,"CANT_VENDIDO")
        lista.add(7,"CANT_NO_VENDIDO")
        lista.add(8,"CANT_NO_VISITADO")
        lista.add(9,"SEMANA")
        lista.add(10,"PORC")
        return lista
    }
    /*private fun camposTablaCcvMotivoSolTarjCred(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_MOTIVO")
        lista.add(1,"IND_FOTO")
        lista.add(2,"DESC_MOTIVO")
        return lista
    }*/
    private fun camposTablaSvmPromocionesArtCab(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"NRO_PROMOCION")
        lista.add(3,"COD_UNID_NEGOCIO")
        lista.add(4,"TIP_CLIENTE")
        lista.add(5,"DESCRIPCION")
        lista.add(6,"COMENTARIO")
        lista.add(7,"COD_CONDICION_VENTA")
        lista.add(8,"FEC_VIGENCIA")
        lista.add(9,"COD_ARTICULO")
        lista.add(10,"DESC_ARTICULO")
        lista.add(11,"COD_UNIDAD_MEDIDA")
        lista.add(12,"REFERENCIA")
        lista.add(13,"IND_TIPO")
        lista.add(14,"MULT")
        lista.add(15,"COD_LISTA_PRECIO")
        lista.add(16,"IND_COMBO")
        lista.add(17,"IND_PROM")
        lista.add(18,"IND_ART")
        lista.add(19,"CANT_VENTA")
        return lista
    }
    private fun camposTablaSvmPromocionesArtDet(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"NRO_PROMOCION")
        lista.add(3,"COD_UNID_NEGOCIO")
        lista.add(4,"CANT_DESDE")
        lista.add(5,"CANT_HASTA")
        lista.add(6,"COD_ARTICULO")
        lista.add(7,"COD_UNIDAD_MEDIDA")
        lista.add(8,"DESC_UND_MEDIDA")
        lista.add(9,"IND_TIPO")
        lista.add(10,"DESCUENTO")
        lista.add(11,"PRECIO_GS")
        lista.add(12,"IND_MULTIPLE")
        lista.add(13,"PRECIO_RS")
        return lista
    }
    private fun camposTablaSvmMensajeConclusion(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"IND_LOGRADO")
        lista.add(3,"RESULTADO")
        return lista
    }
    private fun camposTablaSvmSurtidoEficiente(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"COD_CLIENTE")
        lista.add(3,"COD_SUBCLIENTE")
        lista.add(4,"TIP_CLIENTE")
        lista.add(5,"COD_ARTICULO")
        lista.add(6,"TIP_SURTIDO")
        return lista
    }
    private fun camposTablaSvmLiqPremiosVend(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"TIP_COM")
        lista.add(3,"COD_MARCA")
        lista.add(4,"DESC_MARCA")
        lista.add(5,"MONTO_VENTA")
        lista.add(6,"MONTO_META")
        lista.add(7,"PORC_COBERTURA")
        lista.add(8,"PORC_LOG")
        lista.add(9,"MONTO_A_COBRAR")
        lista.add(10,"MONTO_COBRAR")
        lista.add(11,"TOT_CLIENTES")
        lista.add(12,"CLIENTES_VISITADOS")
        return lista
    }
    private fun camposTablaSvmProduccionSemanalVend(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"CANTIDAD")
        lista.add(3,"SEMANA")
        lista.add(4,"FECHA")
        lista.add(5,"MONTO_VIATICO")
        lista.add(6,"MONTO_TOTAL")
        lista.add(7,"PERIODO")
        return lista
    }
    /*FALTO AGREGAR*/private fun camposTablaSvmRuteoSemanalClienteVend(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"COD_CLIENTE")
        lista.add(3,"COD_SUBCLIENTE")
        lista.add(4,"DESC_CLIENTE")
        lista.add(5,"DIA")
        lista.add(6,"FEC_VISITA")
        return lista
    }
    private fun camposTablaSvmCoberturaVisVendedores(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"COD_GRUPO")
        lista.add(3,"PORC_DESDE")
        lista.add(4,"PORC_HASTA")
        lista.add(5,"PORC_COM")
        return lista
    }
    private fun camposTablaRhvLiquidacionFuerzaVenta(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"FEC_COMPROBANTE")
        lista.add(2,"OBSERVACION")
        lista.add(3,"DESCRIPCION")
        lista.add(4,"TIP_COMPROBANTE_REF")
        lista.add(5,"TOT_IVA")
        lista.add(6,"TOT_GRAVADA")
        lista.add(7,"TOT_EXENTA")
        lista.add(8,"TOT_COMPROBANTE")
        return lista
    }
    private fun camposTablaSvmVtMotivosSodDev(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_MOTIVO")
        lista.add(2,"DESC_MOTIVO")
        return lista
    }
    private fun camposTablaFvvLiqCuotaXUndNegVend(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"COD_UNID_NEGOCIO")
        lista.add(3,"DESC_UNID_NEGOCIO")
        lista.add(4,"MONTO_VENTA")
        lista.add(5,"MONTO_CUOTA")
        lista.add(6,"PORC_PREMIO")
        lista.add(7,"FEC_DESDE")
        lista.add(8,"FEC_HASTA")
        lista.add(9,"PORC_ALC_PREMIO")
        lista.add(10,"MONTO_A_COBRAR")
        return lista
    }
    private fun camposTablaSvmCoberturaMensualVend(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"TOT_CLI_CART")
        lista.add(3,"CANT_POSIT")
        lista.add(4,"PORC_COB")
        lista.add(5,"PORC_LOGRO")
        lista.add(6,"FEC_DESDE")
        lista.add(7,"FEC_HASTA")
        lista.add(8,"PREMIOS")
        lista.add(9,"MONTO_A_COBRAR")
        return lista
    }
    private fun camposTablaFvvCobSemanalVend(): ArrayList<String> {
        val lista : ArrayList<String> = ArrayList()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"SEMANA")
        lista.add(3,"TOT_CLIENTES")
        lista.add(4,"CLIENT_VENTAS")
        lista.add(5,"PORC_COBERTURA")
        lista.add(6,"PERIODO")
        lista.add(7,"MONTO_A_COBRAR")
        return lista
    }

//    fun camposTablaS(): ArrayList<String> {
//        var lista : ArrayList<String> = ArrayList()
//        lista.add(0,"")
//        lista.add(1,"")
//        lista.add(2,"")
//        lista.add(3,"")
//        lista.add(4,"")
//        lista.add(5,"")
//        lista.add(6,"")
//        lista.add(7,"")
//        lista.add(8,"")
//        lista.add(9,"")
//        lista.add(10,"")
//        lista.add(11,"")
//        lista.add(12,"")
//        lista.add(13,"")
//        lista.add(14,"")
//        lista.add(15,"")
//        lista.add(16,"")
//        lista.add(17,"")
//        lista.add(18,"")
//        lista.add(19,"")
//        lista.add(20,"")
//        lista.add(21,"")
//        lista.add(22,"")
//        lista.add(23,"")
//        lista.add(24,"")
//        lista.add(25,"")
//        lista.add(26,"")
//        lista.add(27,"")
//        lista.add(28,"")
//        lista.add(29,"")
//        return lista
//    }


}
