package apolo.vendedores.com.utilidades

import java.util.*

class TablasSincronizacion {

//    var tablasReportes : TablasReportes = TablasReportes()
//    var tablasVisitas  : TablasVisitas  = TablasVisitas()
//    var tablasInformes : TablasInformes = TablasInformes()

    fun listaSQLCreateTables(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0, SentenciasSQL.createTableSvm_cliente_vendedor())
        lista.add(1, SentenciasSQL.createTableSvm_articulos_precios())
        lista.add(2, SentenciasSQL.createTableSvm_st_articulos())
        lista.add(3, SentenciasSQL.createTableSvm_vendedor_pedido())
        lista.add(4, SentenciasSQL.createTableSvm_vt_motivos_sd_dev())

        return lista
    }

    fun listaCamposSincronizacion(): Vector<Vector<String>> {
        var lista : Vector<Vector<String>> = Vector<Vector<String>>()
        lista.add(0,camposTablaSvm_cliente_vendedor())
        lista.add(1,camposTablaSvm_articulos_precios())
        lista.add(2,camposTablaSvm_st_articulos())
        lista.add(3,camposTablaSvm_vendedor_pedido())
        lista.add(4,camposTablaSvm_motivos_sd_dev())
        return lista
    }

    fun camposTablaSvm_metas_punto_por_linea(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"DESC_VENDEDOR")
        lista.add(3,"COD_LINEA")
        lista.add(4,"DESC_LINEA")
        lista.add(5,"ABREV")
        lista.add(6,"DESC_GTE_MARKETIN")
        lista.add(7,"DESC_MODULO")
        lista.add(8,"COD_SUPERVISOR")
        lista.add(9,"DESC_SUPERVISOR")
        lista.add(10,"MAYOR_VENTA")
        lista.add(11,"VENTA_3")
        lista.add(12,"VENTA_4")
        lista.add(13,"METAS")
        lista.add(14,"NRO_ORD_MAG")
        lista.add(15,"ORD_GTE_MARK")
        lista.add(16,"ORD_CATEGORIA")
        lista.add(17,"MES_1")
        lista.add(18,"MES_2")
        lista.add(19,"")
        return lista
    }
    fun camposTablaSvm_costo_venta_articulo(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_SUCURSAL")
        lista.add(2,"DESC_SUCURSAL")
        lista.add(3,"COD_ARTICULO")
        lista.add(4,"REFERENCIA")
        lista.add(5,"COSTO_VENTA")
        lista.add(6,"COSTO_VENTA")
        lista.add(7,"")
        return lista
    }
    fun camposTablaSvm_surtido_eficiente(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"DESC_VENDEDOR")
        lista.add(3,"COD_CLIENTE")
        lista.add(4,"COD_SUBCLIENTE")
        lista.add(5,"TIP_CLIENTE")
        lista.add(6,"COD_ARTICULO")
        lista.add(7,"TIP_SURTIDO")
        lista.add(8,"")
        return lista
    }
    fun camposTablaSvm_metas_punto_por_linea_empresa(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"METAS")
        lista.add(2,"VENTA")
        lista.add(3,"CANT_PUNTO")
        lista.add(4,"PUNT_ACUM")
        lista.add(5,"")
        return lista
    }
    fun camposTablaSvm_positivacion_cliente(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"DESC_VENDEDOR")
        lista.add(3,"TIP_CAUSAL")
        lista.add(4,"COD_CLIENTE")
        lista.add(5,"COD_SUBCLIENTE")
        lista.add(6,"DESC_CLIENTE")
        lista.add(7,"DESC_SUBCLIENTE")
        lista.add(8,"DIRECCION")
        lista.add(9,"DESC_CIUDAD")
        lista.add(10,"RUC")
        lista.add(11,"DESC_REGION")
        lista.add(12,"DESC_ZONA")
        lista.add(13,"TELEFONO")
        lista.add(14,"IND_POS")
        lista.add(15,"MONTO_VENTA")
        lista.add(16,"COD_SUPERVISOR")
        lista.add(17,"")
        return lista
    }
    fun camposTablaSvm_premios_supervisores(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_MARCA")
        lista.add(2,"DESC_MARCA")
        lista.add(3,"FEC_COMPROBANTE")
        lista.add(4,"VENTA")
        lista.add(5,"META")
        lista.add(6,"CANT_PUNTO")
        lista.add(7,"PORC_CUMP")
        lista.add(8,"PUNT_ACUM")
        lista.add(9,"")
        return lista
    }
    fun camposTablaSvm_control_general_sup(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_SUPERVISOR")
        lista.add(1,"DESC_SUPERVISOR")
        lista.add(2,"NRO_ORDEN")
        lista.add(3,"METAS")
        lista.add(4,"VENTAS")
        lista.add(5,"PORC_VOL_VENTAS")
        lista.add(6,"PUNT_ACUM_LINEAS")
        lista.add(7,"PUNT_CLI_ACUM")
        lista.add(8,"CANT_CLI_POS")
        lista.add(9,"MONTO_REBOTE")
        lista.add(10,"MONTO_DEV")
        lista.add(11,"CANT_COB")
        lista.add(12,"CANT_RUTEO")
        lista.add(13,"VENTAS_ESTR")
        lista.add(14,"METAS_ESTR")
        lista.add(15,"CATASTRO")
        lista.add(16,"PORC_MONTO_REBOTE")
        lista.add(17,"PORC_MONTO_DEV")
        lista.add(18,"")
        return lista
    }
    fun camposTablaSvm_motivo_analisis_vendedor(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_MOTIVO")
        lista.add(1,"DESCRIPCION")
        lista.add(2,"ESTADO")
        lista.add(3,"PUNTUACION")
        lista.add(4,"COD_VENDEDOR")
        lista.add(5,"COD_GRUPO")
        lista.add(6,"NRO_ORDEN")
        lista.add(7,"")
        return lista
    }
    fun camposTablaSvm_cliente_prom_vendedor(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_CLIENTE")
        lista.add(2,"COD_SUBCLIENTE")
        lista.add(3,"DESC_SUBCLIENTE")
        lista.add(4,"DESC_CLIENTE")
        lista.add(5,"COD_VENDEDOR")
        lista.add(6,"TELEFONO")
        lista.add(7,"RUC")
        lista.add(8,"TIP_CAUSAL")
        lista.add(9,"desc_ciudad")
        lista.add(10,"DESC_ZONA")
        lista.add(11,"DESC_REGION")
        lista.add(12,"DIRECCION")
        lista.add(13,"TELEFONO")
        lista.add(14,"COD_SUCURSAL")
        lista.add(15,"DESC_TIPO")
        lista.add(16,"COD_CONDICION")
        lista.add(17,"DESC_CONDICION")
        lista.add(18,"LIMITE_CREDITO")
        lista.add(19,"TOT_DEUDA")
        lista.add(20,"SALDO")
        lista.add(21,"FEC_VISITA")
        lista.add(22,"IND_VISITA")
        lista.add(23,"COD_ZONA")
        lista.add(24,"TIPO_CONDICION")
        lista.add(25,"IND_DIRECTA")
        lista.add(26,"IND_ATRAZO")
        lista.add(27,"FRECUENCIA")
        lista.add(28,"COMENTARIO")
        lista.add(29,"IND_ESP")
        lista.add(30,"CATEGORIA")
        lista.add(31,"TELEFONO2")
        lista.add(32,"LATITUD")
        lista.add(33,"LONGITUD")
        lista.add(34,"CERCA_DE")
        lista.add(35,"IND_CADUCADO")
        lista.add(36,"TIP_CLIENTE")
        lista.add(37,"IND_VITRINA")
        lista.add(38,"FOTO_FACHADA")
        lista.add(39,"TIEMPO_MIN")
        lista.add(40,"TIEMPO_MAX")
        lista.add(41,"DIAS_INICIAL")
        lista.add(42,"")

        return lista
    }
    fun camposTablaSvm_categoria(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_CATEGORIA")
        lista.add(2,"DESC_CATEGORIA")
        lista.add(3,"COD_SEGMENTO")
        lista.add(4,"DESC_SEGMENTO")
        lista.add(5,"ORDEN")
        lista.add(6,"TIPO")
        lista.add(7,"COD_TIP_CLIENTE")
        lista.add(8,"")
        return lista
    }
    fun camposTablaSvm_retorno_comentario(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"FEC_ENTRADA")
        lista.add(2,"FEC_SALIDA")
        lista.add(3,"COD_PROMOTOR")
        lista.add(4,"COD_CLIENTE")
        lista.add(5,"COD_SUBCLIENTE")
        lista.add(6,"COD_CATEGORIA")
        lista.add(7,"COD_SEGMENTO")
        lista.add(8,"TIPO")
        lista.add(9,"PUNTUACION")
        lista.add(10,"COMENTARIO_SUPERVISOR")
        lista.add(11,"")
        return lista
    }
    fun camposTablaSvm_periodo_foto(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_TIP_CLIENTE")
        lista.add(2,"FEC_INICIO")
        lista.add(3,"FEC_FIN")
        lista.add(4,"")
        return lista
    }
    fun camposTablaSvm_cliente_list_prec(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_CLIENTE")
        lista.add(2,"COD_SUBCLIENTE")
        lista.add(3,"COD_VENDEDOR")
        lista.add(4,"COD_LISTA_PRECIO")
        lista.add(5,"DESC_LISTA")
        lista.add(6,"IND_DEFECTO")
        lista.add(7,"COD_MONEDA")
        lista.add(8,"DECIMALES")
        lista.add(9,"")
        return lista
    }
    fun camposTablaSvm_articulos_precios(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"MODULO")
        lista.add(3,"COD_LISTA_PRECIO")
        lista.add(4,"COD_ARTICULO")
        lista.add(5,"DESC_ARTICULO")
        lista.add(6,"PREC_CAJA")
        lista.add(7,"PREC_UNID")
        lista.add(8,"COD_UNIDAD_MEDIDA")
        lista.add(9,"PORC_IVA")
        lista.add(10,"REFERENCIA")
        lista.add(11,"MULT")
        lista.add(12,"DIV")
        lista.add(13,"IND_LIM_VENTA")
        lista.add(14,"COD_LINEA")
        lista.add(15,"COD_FAMILIA")
        lista.add(16,"COD_BARRA")
        lista.add(17,"CANT_MINIMA")
        lista.add(18,"PORC_DESCUENTO")
        lista.add(19,"")
        return lista
    }
    fun camposTablaSvm_st_articulos(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_ARTICULO")
        lista.add(2,"DESC_ARTICULO")
        lista.add(3,"COD_UNIDAD_REL")
        lista.add(4,"REFERENCIA")
        lista.add(5,"MULT")
        lista.add(6,"DIV")
        lista.add(7,"COD_IVA")
        lista.add(8,"PORC_IVA")
        lista.add(9,"COD_LINEA")
        lista.add(10,"COD_FAMILIA")
        lista.add(11,"CANT_MINIMA")
        lista.add(12,"CANT_EXIST")
        lista.add(13,"COD_BARRA")
        lista.add(14,"IND_BASICO")
        lista.add(15,"")
        return lista
    }
    fun camposTablaSvm_condicion_venta(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"cod_empresa")
        lista.add(1,"cod_condicion_venta")
        lista.add(2,"descripcion")
        lista.add(3,"tipo_condicion")
        lista.add(4,"abreviatura")
        lista.add(5,"dias_inicial")
        lista.add(6,"porc_desc")
        lista.add(7,"porc_desc")
        lista.add(8,"")
        return lista
    }
    fun camposTablaSvm_vendedor_pedido(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"IND_PALM")
        lista.add(3,"TIPO")
        lista.add(4,"SERIE")
        lista.add(5,"NUMERO")
        lista.add(6,"FECHA")
        lista.add(7,"COD_CLI_VEND")
        lista.add(8,"COD_PERSONA")
        lista.add(9,"RANGO")
        lista.add(10,"MIN_FOTOS")
        lista.add(11,"MAX_FOTOS")
        lista.add(12,"PER_VENDER")
        lista.add(13,"PER_PRESENCIAL")
        lista.add(14,"HORA")
        lista.add(15,"VERSION_SISTEMA")
        lista.add(16,"PER_ASISTENCIA")
        lista.add(17,"FRECUENCIA_RASTREO")
        lista.add(18,"HORA_INICIO")
        lista.add(19,"HORA_FIN")
        lista.add(20,"TIEMPO_ASISTENCIA")
        lista.add(21,"IND_FOTO")
        lista.add(22,"MIN_VENTA")
        lista.add(23,"PER_MARC_ASIS")
        lista.add(24,"VENT_CON_MARC")
        lista.add(25,"VERSION")
        lista.add(26,"")


//        lista.add(25,"")
//        lista.add(26,"")
//        lista.add(27,"")
//        lista.add(28,"ULTIMA_VEZ")
//        lista.add(29,"ultima_sincro")
        return lista
    }
    fun camposTablaSvm_cliente_vendedor(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_CLIENTE")
        lista.add(2,"COD_SUBCLIENTE")
        lista.add(3,"DESC_SUBCLIENTE")
        lista.add(4,"DESC_CLIENTE")
        lista.add(5,"COD_VENDEDOR")
        lista.add(6,"TELEFONO")
        lista.add(7,"RUC")
        lista.add(8,"TIP_CAUSAL")
        lista.add(9,"DESC_CIUDAD")
        lista.add(10,"DESC_ZONA")
        lista.add(11,"DESC_REGION")
        lista.add(12,"DIRECCION")
        lista.add(13,"TELEFONO")
        lista.add(14,"COD_SUCURSAL")
        lista.add(15,"DESC_TIPO")
        lista.add(16,"COD_CONDICION")
        lista.add(17,"DESC_CONDICION")
        lista.add(18,"LIMITE_CREDITO")
        lista.add(19,"TOT_DEUDA")
        lista.add(20,"SALDO")
        lista.add(21,"FEC_VISITA")
        lista.add(22,"IND_VISITA")
        lista.add(23,"COD_ZONA")
        lista.add(24,"TIPO_CONDICION")
        lista.add(25,"IND_DIRECTA")
        lista.add(26,"IND_ATRAZO")
        lista.add(27,"FRECUENCIA")
        lista.add(28,"COMENTARIO")
        lista.add(29,"IND_ESP")
        lista.add(30,"CATEGORIA")
        lista.add(31,"TELEFONO2")
        lista.add(32,"LATITUD")
        lista.add(33,"LONGITUD")
        lista.add(34,"CERCA_DE")
        lista.add(35,"IND_CADUCADO")
        lista.add(36,"TIP_CLIENTE")
        lista.add(37,"IND_VITRINA")
        lista.add(38,"FOTO_FACHADA")
        lista.add(39,"TIEMPO_MIN")
        lista.add(40,"TIEMPO_MAX")
        lista.add(41,"SOL_TARG")
        lista.add(42,"DIAS_INICIAL")
        lista.add(43,"")
        return lista
    }
    fun camposTablaSvm_ultima_venta_cliente(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_CLIENTE")
        lista.add(2,"COD_VENDEDOR")
        lista.add(3,"COD_SUBCLIENTE")
        lista.add(4,"FEC_COMPROBANTE")
        lista.add(5,"COD_ARTICULO")
        lista.add(6,"PRECIO_UNITARIO")
        lista.add(7,"CANTIDAD")
        lista.add(8,"DESC_UNIDAD")
        lista.add(9,"SIGLAS")
        lista.add(10,"DESC_ARTICULO")
        lista.add(11,"DECIMALES")
        lista.add(12,"")
        return lista
    }
    fun camposTablaSvm_prom_articulos_tar_cred(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"NRO_PROMOCION")
        lista.add(2,"COD_CONDICION_VENTA")
        lista.add(3,"COD_ARTICULO")
        lista.add(4,"DESC_ARTICULO")
        lista.add(5,"PORC_DESCUENTO")
        lista.add(6,"DESCRIPCION")
        lista.add(7,"COMENTARIO")
        lista.add(8,"")
        return lista
    }
    fun camposTablaSvm_cond_venta_vendedor(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"COD_LISTA_PRECIO")
        lista.add(3,"COD_CLIENTE")
        lista.add(4,"COD_SUBCLIENTE")
        lista.add(5,"COD_CONDICION_VENTA")
        lista.add(6,"")
        return lista
    }
    fun camposTablaSvm_motivo_no_venta(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_MOTIVO")
        lista.add(2,"CIERRA")
        lista.add(3,"DESC_MOTIVO")
        lista.add(4,"")
        return lista
    }
    fun camposTablaSvm_promociones_perfilMerc(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"TIP_CLIENTE")
        lista.add(2,"NRO_PROMOCION")
        lista.add(3,"DESCRIPCION")
        lista.add(4,"COMENTARIO")
        lista.add(5,"FEC_INI_PROMO")
        lista.add(6,"FEC_FIN_PROMO")
        lista.add(7,"COD_ARTICULO")
        lista.add(8,"")
        return lista
    }
    fun camposTablaSvm_promociones_art_cab(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"NRO_PROMOCION")
        lista.add(3,"COD_UNID_NEGOCIO")
        lista.add(4,"TIP_CLIENTE")
        lista.add(5,"DESCRIPCION")
        lista.add(6,"COMENTARIO")
        lista.add(7,"COD_CONDICION_VENTA")
        lista.add(8,"FEC_VIGENCIA")
        lista.add(9,"COD_ARTICULO")
        lista.add(10,"DESC_ARTICULO")
        lista.add(11,"COD_UNIDAD_MEDIDA")
        lista.add(12,"REFERENCIA")
        lista.add(13,"IND_TIPO")
        lista.add(14,"MULT")
        lista.add(15,"COD_LISTA_PRECIO")
        lista.add(16,"IND_COMBO")
        lista.add(17,"IND_PROM")
        lista.add(18,"IND_ART")
        lista.add(19,"CANT_VENTA")
        lista.add(20,"")
        return lista
    }
    fun camposTablaSvm_promociones_art_det(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"NRO_PROMOCION")
        lista.add(3,"COD_UNID_NEGOCIO")
        lista.add(4,"CANT_DESDE")
        lista.add(5,"CANT_HASTA")
        lista.add(6,"COD_ARTICULO")
        lista.add(7,"COD_UNIDAD_MEDIDA")
        lista.add(8,"DESC_UND_MEDIDA")
        lista.add(9,"IND_TIPO")
        lista.add(10,"DESCUENTO")
        lista.add(11,"PRECIO_GS")
        lista.add(12,"IND_MULTIPLE")
        lista.add(13,"PRECIO_RS")
        lista.add(14,"")
        return lista
    }
    fun camposTablaSvm_produccion_semanal_vend(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"COD_PERSONA")
        lista.add(3,"DESC_VENDEDOR")
        lista.add(4,"CANTIDAD")
        lista.add(5,"SEMANA")
        lista.add(6,"FECHA")
        lista.add(7,"MONTO_VIATICO")
        lista.add(8,"MONTO_TOTAL")
        lista.add(9,"PERIODO")
        lista.add(10,"")
        return lista
    }
    fun camposTablaSvm_cobertura_marca_sup(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"PORC_DESDE")
        lista.add(2,"PORC_HASTA")
        lista.add(3,"PORC_COM")
        lista.add(4,"LINHA")
        lista.add(5,"")
        return lista
    }
    fun camposTablaSvm_cobertura_vis_vendedores(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_GRUPO")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"DESC_VENDEDOR")
        lista.add(3,"PORC_DESDE")
        lista.add(4,"PORC_HASTA")
        lista.add(5,"PORC_COM")
        lista.add(6,"")
        return lista
    }
    fun camposTablaSvm_motivos_sd_dev(): Vector<String> {
        var lista : Vector<String> = Vector<String>()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_MOTIVO")
        lista.add(2,"DESC_MOTIVO")
        lista.add(3,"")
        return lista
    }

//    fun camposTablaS(): Vector<String> {
//        var lista : Vector<String> = Vector<String>()
//        lista.add(0,"")
//        lista.add(1,"")
//        lista.add(2,"")
//        lista.add(3,"")
//        lista.add(4,"")
//        lista.add(5,"")
//        lista.add(6,"")
//        lista.add(7,"")
//        lista.add(8,"")
//        lista.add(9,"")
//        lista.add(10,"")
//        lista.add(11,"")
//        lista.add(12,"")
//        lista.add(13,"")
//        lista.add(14,"")
//        lista.add(15,"")
//        lista.add(16,"")
//        lista.add(17,"")
//        lista.add(18,"")
//        lista.add(19,"")
//        lista.add(20,"")
//        lista.add(21,"")
//        lista.add(22,"")
//        lista.add(23,"")
//        lista.add(24,"")
//        lista.add(25,"")
//        lista.add(26,"")
//        lista.add(27,"")
//        lista.add(28,"")
//        lista.add(29,"")
//        return lista
//    }


}